version: "3.5"

services:
  ghmongo:
    image: mongo:4.0.6
    ports:
    - 27000:27017
    environment:
    - MONGO_INITDB_ROOT_USERNAME=mongo-admin
    - MONGO_INITDB_ROOT_PASSWORD=mongo-pass
    - MONGO_INITDB_DATABASE=github
    volumes:
    - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    - ./gh_mongo_data:/data/db
    - ./gh_mongo_dumps:/gh_mongo_dumps
    - ./gh_mongo_scripts/:/gh_mongo_scripts
  ghmaria:
    image: mariadb:10.4.2
    ports:
    - 3300:3306
    environment:
      MYSQL_ROOT_PASSWORD: maria-pass
      MYSQL_DATABASE: github
      MYSQL_USER: github-user
      MYSQL_PASSWORD: github-pass
    volumes:
    - ./gh_maria_data:/var/lib/mysql
    - ./gh_maria_dumps:/gh_maria_dumps
    - ./gh_maria_scripts/:/gh_maria_scripts
networks:
  default:
    name: codescoop-stack
